### ISSUE TITLE
Hash Algorithms

### ISSUE THREAD

**Issue by ebosetalee** [ebosetalee/ds-and-algos#12]
Proposed Hash Algo
1. input the string argument n
2. find the ascii value of each character in n
3. add the ascii values as value
4. return the remainder of value divided by 1000 

Hash function example:
```
Start
input "Raymond"
R = 82, a = 97, y = 121, m = 109, o = 111, n = 110, d = 100
82 + 97 + 121 + 109 + 111 + 110 + 100 = 730
return 730 % 1000 = 730
End
```

See code stub below
```py
def awesome_hash_func(value=None):
    # do awesome stuff here
    return awesome_hash_value

hash_value = awesome_hash_func("raymond")
print(hash_value) # prints 730
```

A hash table has some major operations which are `get`, `set`, `delete`, `has`, `hash`, `get_keys`

The tests should look something like this
```py
hash_table = HashTable()
value = hash_table.set("Raymond")
self.assertEqual(hash_table.value.get("Raymond"), 730)
self.assertEqual(hash_table.get_keys(), {730: "Raymond"})
```

**Comment by jirevwe** [comment]
Why are we stopping at 100? A hash table with only 100 items will have a lot of collisions. Let's use 1000

**Comment by jirevwe** [comment]
Also add live examples with the calculation of the hash for a particular input and show the output

**Comment by ebosetalee** [comment]
> Why are we stopping at 100? A hash table with only 100 items will have a lot of collisions. Let's use 1000

It'll bring a float if the calculations aren't above 1000
except i use id instead

**Comment by jirevwe** [comment]
Use the modulos then. That will give you a whole number

**Comment by ebosetalee** [comment]
module is 10 @jirevwe right?

**Comment by jirevwe** [comment]
@ebosetalee I've updated it
